/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Member = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'customFields' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'registrationDate' : IDL.Int,
  'phoneNumber' : IDL.Text,
  'membershipType' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const FormField = IDL.Record({
  'fieldLabel' : IDL.Text,
  'required' : IDL.Bool,
  'options' : IDL.Opt(IDL.Vec(IDL.Text)),
  'fieldType' : IDL.Text,
});
export const RegistrationForm = IDL.Record({ 'fields' : IDL.Vec(FormField) });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentForm' : IDL.Func([], [IDL.Opt(RegistrationForm)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerMember' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
      ],
      [IDL.Nat],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadForm' : IDL.Func([RegistrationForm], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Member = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'customFields' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'registrationDate' : IDL.Int,
    'phoneNumber' : IDL.Text,
    'membershipType' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const FormField = IDL.Record({
    'fieldLabel' : IDL.Text,
    'required' : IDL.Bool,
    'options' : IDL.Opt(IDL.Vec(IDL.Text)),
    'fieldType' : IDL.Text,
  });
  const RegistrationForm = IDL.Record({ 'fields' : IDL.Vec(FormField) });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllMembers' : IDL.Func([], [IDL.Vec(Member)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentForm' : IDL.Func([], [IDL.Opt(RegistrationForm)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerMember' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
        ],
        [IDL.Nat],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadForm' : IDL.Func([RegistrationForm], [], []),
  });
};

export const init = ({ IDL }) => { return []; };