/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FormField {
  'fieldLabel' : string,
  'required' : boolean,
  'options' : [] | [Array<string>],
  'fieldType' : string,
}
export interface Member {
  'id' : bigint,
  'status' : string,
  'fullName' : string,
  'email' : string,
  'customFields' : Array<[string, string]>,
  'registrationDate' : bigint,
  'phoneNumber' : string,
  'membershipType' : string,
}
export interface RegistrationForm { 'fields' : Array<FormField> }
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllMembers' : ActorMethod<[], Array<Member>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentForm' : ActorMethod<[], [] | [RegistrationForm]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerMember' : ActorMethod<
    [string, string, string, string, Array<[string, string]>],
    bigint
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'uploadForm' : ActorMethod<[RegistrationForm], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];